/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alibaba_athena_base_ALJniActivity */

#ifndef _Included_com_alibaba_athena_base_ALJniActivity
#define _Included_com_alibaba_athena_base_ALJniActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alibaba_athena_base_ALJniActivity
 * Method:    stringTestNdk
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_alibaba_athena_1base_ALJniActivity_stringTestNdk
  (JNIEnv *, jobject);

/*
 * Class:     com_alibaba_athena_base_ALJniActivity
 * Method:    decompressAndUnzip
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_alibaba_athena_1base_ALJniActivity_decompressAndUnzip
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
